# Generated by Django 2.2.9 on 2020-01-28 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logininfo',
            name='password',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
