# Generated by Django 2.2.9 on 2020-01-31 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20200128_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='logininfo',
            name='email',
            field=models.CharField(default='test@gmail.com', max_length=150),
            preserve_default=False,
        ),
    ]
