# Generated by Django 2.2.9 on 2020-03-07 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_auto_20200214_0417'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yelpdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('clickdata', models.CharField(max_length=1000)),
                ('clicktime', models.IntegerField()),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
            ],
        ),
    ]
