# Generated by Django 2.2.9 on 2020-03-07 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_yelpuserreviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='YelpRecommedations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.CharField(max_length=200)),
                ('restaurant', models.CharField(max_length=200)),
                ('rating', models.IntegerField()),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
            ],
        ),
    ]
