# Generated by Django 2.2.9 on 2020-04-05 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_yelprecommedations'),
    ]

    operations = [
        migrations.AddField(
            model_name='logininfo',
            name='fromgoogle',
            field=models.BooleanField(default=False),
        ),
    ]
