# Generated by Django 2.2.9 on 2020-06-26 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_logininfo_fromgoogle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='database.LoginInfo')),
                ('notecount', models.IntegerField(verbose_name=0)),
                ('tagcount', models.IntegerField(verbose_name=0)),
            ],
        ),
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('timelogged', models.IntegerField()),
                ('clickdata', models.CharField(max_length=1000)),
                ('ipaddress', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Yelpdata',
        ),
        migrations.DeleteModel(
            name='YelpRecommedations',
        ),
        migrations.DeleteModel(
            name='YelpUserReviews',
        ),
        migrations.AlterField(
            model_name='logininfo',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
