# Generated by Django 2.2.9 on 2020-06-26 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_auto_20200625_2300'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notes',
        ),
    ]
