# Generated by Django 2.2.9 on 2020-06-27 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_logininfo_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logininfo',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
