# Generated by Django 2.2.9 on 2020-06-27 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0014_auto_20200627_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='logininfo',
            name='googleid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
