# Generated by Django 2.2.9 on 2020-06-27 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0015_logininfo_googleid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logininfo',
            name='googleid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
